### Site
repository: SabrinaMokhtari/sabrinamokhtari.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

### Content configuration version
version: 2

### Personal info
name: Sabrina Mokhtari
# title: Your job title
email: sabrinamokhtari98@gmail.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

### Dark Mode (true/false/never)
darkmode: false

### Social links
github_username:  SabrinaMokhtari
linkedin_username: sabrina-mokhtari

### Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

### Google Analytics and Tag Manager
### Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

### About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/me.jpeg
about_content: | 
  **CV: [PDF](https://sabrinamokhtari.github.io/files/CV.pdf)**

  My name is Sabrina Mokhtari. I am currently a first-year **Master's** student at **University of Waterloo**, 
  working under the supervision of **Prof.** [**Gautam Kamath**] (http://www.gautamkamath.com/). Previously, 
  I was a **Computer Engineering** student at **Sharif University of Technology**, Where I worked as an undergrad 
  research assistant on improving the robustness of vision transformers under the supervision of **Prof.** [Mohammad Hossein Rohban](http://sharif.ir/~rohban/). 
  Before that, I worked as a **data engineer** at [**Wizeanalytics Startup**](https://www.linkedin.com/company/wizeanalytics/?originalSubdomain=ir) under the supervision
  of **Prof.** [**Hamid R. Rabiee**](http://sharif.edu/~rabiee/), where I was part of the **Machine Learning** team and worked on an AI-driven big data processing 
  platform that establishes methods on the data storage layer and distributed big data processing to facilitate predictive analytics. My research interests are 
  computer vision, privacy in machine learning, and robustness.

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       border: weak  # Value of `weak` will display a weak border below this item. # Any 
  #                     # other value (or no value) means no border will be displayed
  #       title: Project name
  #       link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       link_text: Link Text
  #       additional_links:
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       quote: >
  #         Short overview of the project (optional)
  #       description: | 
  #         Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Robust and Interpretable Deep Learning Laboratory
        sub_title: Research Assistant
        caption: June 2021 - September 2022
        description: | 
          I worked on various techniques to train trustworthy vision transformers that are not readily affected by malicious perturbations.
      
      - layout: left
        title: Wizeanalytics Startup
        sub_title: Data Engineer
        caption: August 2020 - March 2021
        description: | 
          Wizeanalytics works on designing an AI-driven big data processing platform that establishes methods on the data storage layer and 
          distributed big data processing to facilitate predictive analytics. I joined [**Wizeanalytics Startup**](https://www.linkedin.com/company/wizeanalytics/?originalSubdomain=ir) 
          as an intern and primarily worked on BI systems. During my internship I worked on big data processing systems such as Apache Kafka 
          and enabled our platform to work with and analyze real-time data streaming by connecting the system to Apache Kafka. After my internship, 
          I joined the **Machine Learning** team and helped design and implement a comprehensive preprocessing pipeline. To that end, I developed 
          several text processing features such as text spell correction, text normalization, and string obfuscation.

     - layout: left
        title: Intelligent Information Solutions Center
        sub_title: Software Developer
        caption: June 2019 - September 2019
        description: | 
          Intelligent Information Solutions Center works on a website that helps create domestic social networks. It allows companies, academic 
          societies, and other social groups to create custom social networks to serve as alternatives to popular global platforms. I joined the 
          Intelligent Information Solutions Center as a software developer and worked with the software maintenance team, where I helped improve 
          the system’s functionality by designing new features and upgrading and repairing the software when needed.
          
      - layout: left
        title: Sharif University of Technology
        sub_title: Teaching Assistant
        caption: Februrary 2019 - July 2021
        description: | 
          since my second semester, I have collaborated as a **teaching assistant** with several
          faculty members of **computer engineering department**. all courses that I have contributed are listed below:

          **Spring 2021**
          - Database Design, Prof. Abbas Heydarnoori:
          - Linear Algebra, Prof. Hamid Reza Rabiee
          
          
          **Fall 2021**
          - Systems Analysis and Design, Prof. Abbas Heydarnoori
          - Artificial Intelligence, Prof. Mohammad Hossein Rohban
          
          
          **Fall 2020**
          - Linear Algebra, Prof. Hamid Reza Rabiee
         

  - title: Education
    layout: list
    content:
    - layout: left
        title: University of Waterloo
        sub_title: MMath in Computer Science
        supervisor: [Gautam Kamath] (http://www.gautamkamath.com/)
        caption: 2022-present
        # quote: >
        #   Short institution or course description (optional)
        
      - layout: left
        title: Sharif University of Technology
        sub_title: B.Sc. Computer Engineering
        caption: 2017-2022
        # quote: >
        #   Short institution or course description (optional)
        description: | 
          GPA: 18.40/20

          **Related courses**

          artificial intelligence, linear algebra, machine learning,
          data structures and algorithms, modern information retrieval,
          design of algorithms, probability and statistics, discrete structures.

  - title: A Little More About Me
    layout: text
    content: | 
      Alongside my interests in science and technology, some of my other hobbies are:
        - Horseback Riding
        - Basketball playing
        - Random Walking:))
### Footer
footer_show_references: true
# references_title: References on request (Override references text)

### Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
