### Site
repository: SabrinaMokhtari/sabrinamokhtari.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

### Content configuration version
version: 2

### Personal info
name: Sabrina Mokhtari
# title: Your job title
email: sabrinamokhtari98@gmail.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

### Dark Mode (true/false/never)
darkmode: false

### Social links
github_username:  SabrinaMokhtari
linkedin_username: sabrina-mokhtari

### Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

### Google Analytics and Tag Manager
### Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

### About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/me.jpeg
about_content: | 
  **CV: [PDF](https://SabrinaMokhtari/sabrinamokhtari.github.io/files/CV.pdf)**

  My name is Sabrina Mokhtari and currently I am a first year **Compuer Science** master's student at **Waterloo University**,
  Working under the supervision of [**Prof. Gautam Kamath.**](http://www.gautamkamath.com/).
  
  

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       border: weak  # Value of `weak` will display a weak border below this item. # Any 
  #                     # other value (or no value) means no border will be displayed
  #       title: Project name
  #       link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       link_text: Link Text
  #       additional_links:
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       quote: >
  #         Short overview of the project (optional)
  #       description: | 
  #         Description about the work on/with the project
  - title: Experience
    layout: list
    content:
       - layout: left
        title: Sharif University of Technology
        sub_title: Research Assistant
        caption: June 2021, September 2022
        description: | 
          Description
          
      - layout: left
        title: Wizeanalytics Startup
        sub_title: Data Engineer
        caption: August 2020 - September 2021
        link: https://www.linkedin.com/company/wizeanalytics/?originalSubdomain=ir
        description: | 
          Description 

      - layout: left
        title: Sharif University of Technology
        sub_title: Teaching Assistant
        caption: Februrary 2019 - July 2021
        description: | 
          since my second semester, I have collaborated as a **teaching assistant** with several
          faculty members of **computer engineering department**. all courses that I have contributed are listed below:
          
          
          **Fall 2020**
          - Artificial intelligence, Dr. Rohban
          - Linear algebra, Prof. Rabiee

  - title: Education
    layout: list
    content:
      - layout: left
        title: Sharif University of Technology
        sub_title: B.Sc. Computer Engineering
        caption: 2017-2022
        # quote: >
        #   Short institution or course description (optional)
        description: | 
          GPA: 18.40/20

          **Related courses**

          Convolutional neural networks for visual recognition (audited, online Stanford),
          machine learning (audited, online Stanford), artificial intelligence, linear algebra,
          data structures and algorithms, introduction to bioinformatics, modern information retrieval,
          design of algorithms, probability and statistics, discrete structures.
      

  - title: A Little More About Me
    layout: text
    content: | 
      Alongside my interests in science and technology, some of my other hobbies are:
        - Horseback riding
### Footer
footer_show_references: true
# references_title: References on request (Override references text)

### Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
